use_frameworks!

target 'SWProject_Example' do
  pod 'SWProject', :path => '../'

  target 'SWProject_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
